services:
  # 1. PHP Service (Backend)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-inertia-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  # 2. Nginx Service (Web Server)
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network

  # 3. MySQL Service (Database)
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - "3307:3306"
    networks:
      - laravel-network

  # 4. Node Service (Frontend - Vite/React)
  node:
    image: node:20-alpine
    container_name: laravel-node
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173" # Port mặc định của Vite
    tty: true
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge